field: ef8f14e3-3f96-4dd0-8f89-6fcd65df2937 # VB
fieldLayouts:
  7807c194-5e11-454f-b9f6-3d286907a88d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: df954f9d-81aa-486d-afe8-01f3e13e1be6 # Naam
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2cbdc00f-9c09-4cfb-ac5b-3c3d0632b593
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c1ae60f4-7ea2-4c9b-9291-3d4bad942f10 # Telefoon
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d350734c-de1e-49eb-9faf-25095d4dae16
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f6bedd2f-0ebe-45b0-befa-e4367e7d206e # foto
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fdf64fbf-83ee-448a-9fe6-952f9f538d88
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ca358acb-4e24-4612-a770-be947c2d48be
        userCondition: null
fields:
  c1ae60f4-7ea2-4c9b-9291-3d4bad942f10: # Telefoon
    columnSuffix: jwoatgpe
    contentColumnType: text
    fieldGroup: null
    handle: telefoon
    instructions: null
    name: Telefoon
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  df954f9d-81aa-486d-afe8-01f3e13e1be6: # Naam
    columnSuffix: drvyvsqx
    contentColumnType: text
    fieldGroup: null
    handle: naam
    instructions: null
    name: Naam
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  f6bedd2f-0ebe-45b0-befa-e4367e7d206e: # foto
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: foto
    instructions: null
    name: foto
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      branchLimit: null
      defaultUploadLocationSource: 'volume:bd1e2832-cdcd-433c-98d5-de4b648a9218' # Uploads
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:bd1e2832-cdcd-433c-98d5-de4b648a9218' # Uploads
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: begeleider
name: begeleider
sortOrder: 1
