field: 3369e536-f2fb-46b5-b061-ea577eeeb05d # Groepen
fieldLayouts:
  5ec087b7-7628-40c5-87d2-722d882bb90e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 709b88a0-b344-4829-92be-3ef1a838a02d # Groepsnaam
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dc6bf105-23bd-4870-807f-06310e776436
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 995ac54b-83f6-4408-975e-440ea1f33d57 # Leeftijd
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0fa09df9-6356-4a42-850b-ed4182370d77
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c0b8c2a6-4263-4aba-b66f-71388eaae9a5 # Leiding
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9b75de38-6578-48d3-b4cc-d22499bdaa84
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4fa75f6b-f4a0-4158-b2a8-97a13e854179 # Verantwoordelijke
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 31579741-3efb-4642-8dc3-393bf69a761d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c81e8ed9-879e-4966-824f-10e4b3a8327c # Leidingsfoto
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2cd496bf-57f3-4970-b2e7-c27b18faad4b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: a8ca19bc-809b-42cb-8422-fa49d371f200
        userCondition: null
fields:
  4fa75f6b-f4a0-4158-b2a8-97a13e854179: # Verantwoordelijke
    columnSuffix: cuawbatz
    contentColumnType: text
    fieldGroup: null
    handle: verantwoordelijke
    instructions: null
    name: Verantwoordelijke
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  709b88a0-b344-4829-92be-3ef1a838a02d: # Groepsnaam
    columnSuffix: cfoolrwl
    contentColumnType: text
    fieldGroup: null
    handle: groepsnaam
    instructions: null
    name: Groepsnaam
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  995ac54b-83f6-4408-975e-440ea1f33d57: # Leeftijd
    columnSuffix: ykoeskeq
    contentColumnType: text
    fieldGroup: null
    handle: leeftijd
    instructions: null
    name: Leeftijd
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  c0b8c2a6-4263-4aba-b66f-71388eaae9a5: # Leiding
    columnSuffix: byuewpdv
    contentColumnType: text
    fieldGroup: null
    handle: leiding
    instructions: null
    name: Leiding
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  c81e8ed9-879e-4966-824f-10e4b3a8327c: # Leidingsfoto
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: leidingsfoto
    instructions: null
    name: Leidingsfoto
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      branchLimit: null
      defaultUploadLocationSource: 'volume:bd1e2832-cdcd-433c-98d5-de4b648a9218' # Uploads
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:bd1e2832-cdcd-433c-98d5-de4b648a9218' # Uploads
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources:
        - 'volume:bd1e2832-cdcd-433c-98d5-de4b648a9218' # Uploads
      targetSiteId: null
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: groep
name: Groep
sortOrder: 1
