field: 3b454631-28c8-4f35-b134-e6ae0db71485 # hoofdleiding
fieldLayouts:
  23bd0d74-90a5-4b93-8872-4c0a1798b58e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 04d5fc6a-f816-4357-88b6-a423622cc4ef # Naam
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e777f060-a101-4af3-88bd-3f27e4c74668
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: abd5bba4-90b1-41af-9756-2eec1acc75f5 # nummer
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 54cf5660-110a-4bba-9245-855b2430a2b4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2299081b-c9e4-4d4d-959b-e082e1023b02 # email
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 12511883-f503-4954-8020-1a71e88f6480
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 39465562-fc39-4473-a1f1-6d7a6af340e4 # foto
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 59fb6298-994c-4b4c-bc5e-8e04a85dccff
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: a15b7ff7-7ae5-4899-ac73-53193afaf466
        userCondition: null
fields:
  04d5fc6a-f816-4357-88b6-a423622cc4ef: # Naam
    columnSuffix: oufozrrs
    contentColumnType: text
    fieldGroup: null
    handle: naam
    instructions: null
    name: Naam
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  2299081b-c9e4-4d4d-959b-e082e1023b02: # email
    columnSuffix: ipmghtqs
    contentColumnType: text
    fieldGroup: null
    handle: email
    instructions: null
    name: email
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  39465562-fc39-4473-a1f1-6d7a6af340e4: # foto
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: foto
    instructions: null
    name: foto
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      branchLimit: null
      defaultUploadLocationSource: 'volume:bd1e2832-cdcd-433c-98d5-de4b648a9218' # Uploads
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:bd1e2832-cdcd-433c-98d5-de4b648a9218' # Uploads
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  abd5bba4-90b1-41af-9756-2eec1acc75f5: # nummer
    columnSuffix: apvvonzf
    contentColumnType: text
    fieldGroup: null
    handle: nummer
    instructions: null
    name: nummer
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: hoofdleiding
name: hoofdleiding
sortOrder: 1
