field: 7edce117-9cac-46c3-99ab-efa911426def # Navigation Links
fieldLayouts:
  44ba0c96-0cf3-4633-bef9-8498c5e81f56:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 4b33d5b8-01c9-46a1-972a-5148eb8f2b60 # Link Text
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 625b3549-d82d-43c7-b66b-2cf20db3df65
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c3c3e4b3-9456-41cd-8c6b-fd58555d4f1b # Link Destination
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 78524279-71c7-4b9f-9064-9328dab83199
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 2abe43ca-11ae-4fa2-b7ed-a0569f5e967d
        userCondition: null
fields:
  4b33d5b8-01c9-46a1-972a-5148eb8f2b60: # Link Text
    columnSuffix: payhvpmp
    contentColumnType: text
    fieldGroup: null
    handle: linkText
    instructions: null
    name: 'Link Text'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  c3c3e4b3-9456-41cd-8c6b-fd58555d4f1b: # Link Destination
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: linkDestination
    instructions: null
    name: 'Link Destination'
    searchable: false
    settings:
      allowSelfRelations: false
      branchLimit: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Entry
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\entries\EntryCondition
      selectionLabel: 'Select an entry'
      showSiteMenu: false
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
handle: link
name: Link
sortOrder: 1
