field: e28af842-143c-419d-8a83-537a7ed84afa # Social media
fieldLayouts:
  48c66f73-8cea-475f-a0f7-387813c88671:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 2ae06722-3b5e-4c18-baa3-bf6b93e9b03e # Medium
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 52f0e860-d679-458e-b4e7-8ac39ceac078
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 10923836-7d90-49be-8b11-cd8bf744dacf # Icon
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 30423f15-cce6-43da-b673-10d264e4801c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7b8ff5cd-1815-4591-8670-14b0a70a1fa0 # mediaLink
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 180c396f-291e-42b9-a17d-bf7212e6bde6
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3f53ffe1-8363-462b-bc19-740d76b4042e
        userCondition: null
fields:
  2ae06722-3b5e-4c18-baa3-bf6b93e9b03e: # Medium
    columnSuffix: etzykxve
    contentColumnType: text
    fieldGroup: null
    handle: medium
    instructions: null
    name: Medium
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  7b8ff5cd-1815-4591-8670-14b0a70a1fa0: # mediaLink
    columnSuffix: ggkeunke
    contentColumnType: string(255)
    fieldGroup: null
    handle: mediaLink
    instructions: null
    name: mediaLink
    searchable: false
    settings:
      maxLength: 255
      types:
        - url
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
  10923836-7d90-49be-8b11-cd8bf744dacf: # Icon
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: icon
    instructions: null
    name: Icon
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      branchLimit: null
      defaultUploadLocationSource: 'volume:bd1e2832-cdcd-433c-98d5-de4b648a9218' # Uploads
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:bd1e2832-cdcd-433c-98d5-de4b648a9218' # Uploads
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources:
        - 'volume:bd1e2832-cdcd-433c-98d5-de4b648a9218' # Uploads
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: media
name: Media
sortOrder: 1
