fieldLayouts:
  c82e24d0-1bda-4475-9fa2-b67104ff106e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 6f74109c-dee7-4ec7-ad6d-84a16c885535
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3369e536-f2fb-46b5-b061-ea577eeeb05d # Groepen
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3e9c3e93-58d7-4008-8788-7f35a2bf320b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 05670015-8394-4fe5-8d46-6ab2e949663a
        userCondition: null
handle: groepen
hasTitleField: false
name: groepen
section: e8e95740-0bae-4d94-81f4-a99d3df35832 # groepen
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
