fieldLayouts:
  e23c2575-99f0-48c4-8e25-9a626e68c45a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 0278f574-a1f8-4988-8357-176b874bb107 # Messages
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 32e97af3-ff6a-407c-9042-d0fbd3eb3ab1
            userCondition: null
            warning: null
            width: 100
        name: Message
        uid: 4b2630a5-b1a0-4686-883e-414511b81e84
        userCondition: null
handle: messages
name: Messages
sortOrder: 3
