fieldLayouts:
  78ee1bd6-c2d8-46a2-9d2a-f978f26b4d8f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: e28af842-143c-419d-8a83-537a7ed84afa # Social media
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d26ab3aa-a8fe-4c9e-932d-bdab653e5b77
            userCondition: null
            warning: null
            width: 100
        name: 'Social media'
        uid: 44f9362f-18b1-4588-b212-d3bab4b536b4
        userCondition: null
handle: socialMedia
name: 'Social Media'
sortOrder: 5
