defaultPlacement: end
enableVersioning: true
handle: home
name: home
propagationMethod: all
siteSettings:
  e720509c-a7f5-4364-88f9-03cae61b365b: # Jokido
    enabledByDefault: true
    hasUrls: true
    template: home.twig
    uriFormat: __home__
type: single
