defaultPlacement: end
enableVersioning: true
handle: info
name: info
propagationMethod: all
siteSettings:
  e720509c-a7f5-4364-88f9-03cae61b365b: # Jokido
    enabledByDefault: true
    hasUrls: true
    template: info.twig
    uriFormat: info
type: single
