defaultPlacement: end
enableVersioning: true
handle: jokidootje
name: '''T Jokidootje'
propagationMethod: all
siteSettings:
  e720509c-a7f5-4364-88f9-03cae61b365b: # Jokido
    enabledByDefault: true
    hasUrls: true
    template: jokidootje.twig
    uriFormat: jokidootje
type: single
