defaultPlacement: end
enableVersioning: true
handle: posts
name: berichten
propagationMethod: all
siteSettings:
  e720509c-a7f5-4364-88f9-03cae61b365b: # Jokido
    enabledByDefault: true
    hasUrls: true
    template: blogs/blog.twig
    uriFormat: 'berichten/{slug}'
type: channel
