defaultPlacement: end
enableVersioning: true
handle: verhuur
name: Verhuur
propagationMethod: all
siteSettings:
  e720509c-a7f5-4364-88f9-03cae61b365b: # Jokido
    enabledByDefault: true
    hasUrls: true
    template: verhuur.twig
    uriFormat: verhuur
type: single
